### ISSUE TITLE
Technology at work - Category page 

### ISSUE THREAD

**Issue by Varunvolvo** [hlxsites/vg-macktrucks-com#865] opened 2024-09-13 11:32 UTC
### Issue Type

Bug

### Summary

New published articles are not appearing in main category page 

### Priority

Medium

### Description

The main category page for Technology at Work is not displaying the recent articles. We also need clarification on below - 
Should we have both category and tags fields in the metadata section ? because Tags are for search filters and categories were used for grouping the magazines.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices.

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com/magazine/categories/technology-at-work
2.  View the list of the articles in the category below

### Expected Results

The recently published article has to be displayed in the top

### Actual Results

The recently published article is not displayed

**Comment by BeckyMedlin** [comment] 2024-09-16 17:16
If this is needed for the new Search functionality, we will need to bump up this priority. @netmanito @mollyaljenkins  Please advise. Thank you!

**Comment by ZoeBeykirch** [comment] 2024-09-26 19:13
Closing this ticket because it has been confirmed as fixed on production, now all articles are appearing under the category pages.

**Closed by ZoeBeykirch** 2024-09-26 19:13 UTC
Labels: Triage, Bugfix, Bulldog magazine
