### ISSUE TITLE
[MackTrucks] CR: New Incentives page with CTA + Modal Form

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#449] opened 2023-09-26 11:35 UTC

**Comment by ZoeBeykirch** [comment] 2023-09-26 19:11
Update - after talking more with our internal teams, we have decided to put this request on hold to be handled as part of the Eloqua to Salesforce migration that will bring over multiple microsites hosted on Eloqua into Adobe as part of a bigger Q4 project. More requirements to come from that project soon :)

**Comment by KJohnsn** [comment] 2023-10-03 13:52
**Link:**
https://info.macktrucks.com/Incentives#

**Description**
The Incentives microsite currently resides in Eloqua. We need to replicate the content on the page exactly as it is within Adobe Franklin. The HTML and stylesheets can't be moved over since they will not hold and therefore, we will need a new landing page/microsite made for this.

![Incentives microsite](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/52311faf-c660-4636-86f9-e13ca19c8719)

Once the page is set up in Franklin, then the campaign editors would need to be trained on how to update or create a new Incentive page in the future.

- The top portion of the page features a video module which loops continuously.
- The image and text content areas alternate down the page.
- The CTAs in the content sections have a Get Offer CTA which opens up a form fly out module 
![flex pay promotion flyout](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/fe97bf31-40d8-43a8-b36e-68214cdebe85)
- and the Details CTA opens up a Information fly out module
![Details fly out](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/08340d4b-65d2-48f2-9d66-24f06595f1a2)

The header that is used for this page is the one with the country selector. The footer is the Mack Born Ready footer with the black background.

**Acceptance Criteria**
- The page look and feel matches the Eloqua version exactly
- The functionality works the same on the Adobe Franklin page as it does in the Eloqua page
- The correct header and footer are part of this page - Country selector header and Mack Born Ready footer with black background

**Comment by ZoeBeykirch** [comment] 2024-08-21 19:52
Closing as this is a duplicate of https://github.com/hlxsites/vg-macktrucks-com/issues/523

**Closed by ZoeBeykirch** 2024-08-21 19:52 UTC
Labels: Enhancement
