### ISSUE TITLE
Bug: URGENT | V2 Accordion | Text-only content in accordion not displaying

### ISSUE THREAD

**Issue by WendyKruger** [hlxsites/vg-macktrucks-com#856] opened 2024-09-06 00:05 UTC
### Issue Type

Bug

### Summary

[v2 accordion] Text-only content in accordion not displaying

### Priority

Critical

### Description

The v2 accordion pulls in content either by referencing a block id or adding content directly to the table. Currently only the first line of normal-formatted text is pulling in to the accordion. 

**This is a MAJOR, URGENT issue as it is affecting several live, high-traffic, high-priority pages** including the following:

[Incentives](https://www.macktrucks.com/buy-mack/incentives/)
[Mack Trucks Live Tour](https://www.macktrucks.com/live-tour/#faqs)

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices.

### Steps to Reproduce

First example:
1. Navigate to https://www.macktrucks.com/buy-mack/incentives/
2. Open the Details accordion under Vocational Service Advantage. 

Second example:
1. Navigate to https://www.macktrucks.com/live-tour/#faqs
2. Open the last accordion

### Expected Results

All text should display in the accordion.

### Actual Results

Only the first line of normal text (non-heading) is shown in the accordion.

![image](https://github.com/user-attachments/assets/fd0624c7-1885-4b58-8009-17b225cd1a42)
![image](https://github.com/user-attachments/assets/41c11017-9f2c-4717-9de1-052ce05a8859)

Page inspection shows that only that text is being pulled into the page.

![image](https://github.com/user-attachments/assets/b313544c-fa4a-4515-920d-cb94626fec10)
![image](https://github.com/user-attachments/assets/606816d1-6a7c-4286-90f8-0aa3cc91a570)

While the content is in fact there in the table 

![image](https://github.com/user-attachments/assets/fb0ffe3c-ae2f-4f89-9c2d-9688cf3653bc)
![image](https://github.com/user-attachments/assets/b87a9a4f-00a0-4830-95da-fb844d916ed6)

**Comment by WendyKruger** [comment] 2024-09-06 00:08
CC: @jrcooke12, @BeckyMedlin, @Joesturbo, @ZoeBeykirch, @CasiMcDaniel

**Comment by cincplug** [comment] 2024-09-06 11:27
I checked the issue and here are my findings:

- accordion content on https://www.macktrucks.com/buy-mack/incentives/ page appears with just one row of text because FE script expects either a single link or a single paragraph of text with no HTML at all, which means just plain text without line breaks or any formatting, while the content on Sharepoint https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BFB512D13-B4C4-4284-87CA-C777EBC3EA89%7D&file=index.docx&action=default&mobileredirect=true has several sorts of it: subscript, bulleted list, italics etc
- I assume that one paragraph expectation is in FE script in order to follow the design, because here is how it looks in Sidekick library: https://develop--vg-macktrucks-com--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-accordion&index=0)
- trying to tweak this expectation would bring the risk of breaking functionality in unpredictable ways. Also, subscripts, italics and other elements aren't in the design and I assume the designer wanted to keep it simple for UX reasons like reducing cognitive load on the user, or to avoid having too much to scroll on the mobile device
- if there is a need to have more complex accordion item with various formatting, then we need to develop a new block / variation, for which a designer needs to determine what elements can be there and how would each of them look like, and then the development needs to come up with specification of what formatting should be used by content editors

To fix the current bug, the only safe option for now is to have it like it's specified – with just a single paragraph of text, no formatting

**Comment by BeckyMedlin** [comment] 2024-09-06 12:55
@cincplug @girishdigrajkar @mollyaljenkins Please investigate and determine root cause of why the formatting broke. Wendy 
updated the Incentives page on August 7 and had no issues at that time. Thank you!

**Comment by cincplug** [comment] 2024-09-09 10:23
Hi Becky, we were looking into the root cause, and for now I see a relation to several factors:

- versions of incentives page where the content is correctly displaying use v2-specifications block for details about offers, for example https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/incentives/, while those where content is missing do not use it, for example this one which I took from version history and published in my drafts folder to compare: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/luka/friday6-9
- there was a helix upgrade, in which AEM checks for text nodes not enclosed into any HTML element and wraps them into paragraph element, which delivers different HTML structure then the one that our script expected
- beside v2-accordion block there is also an old accordion block, which might have been accidentally used at some moment, because last Friday Girish gave me a clue that the first accordion actually renders correctly while others don't, and then by looking into raw HTML version of the page I saw that the first accordion used an old accordion block, which was in line with outdated helix. But meanwhile the page was updated with v2-specifications block and now it works

So there are few confusing factors, but my assumption is that using v2-specifications block is the way to go

**Comment by WendyKruger** [comment] 2024-09-09 12:25
I had to completely redo the incentives page since it’s a widely visited page. I agree the v2 specifications block works for now, but still we need to have the issue with text directly in the accordion fixed.
________________________________

**Comment by girishdigrajkar** [comment] 2024-10-08 08:48
Validated and able to see the text/details rather than only single line.
**Bullet point text does not have bullet sign**, except this point all viewports shows all text unlike earlier.

![image](https://github.com/user-attachments/assets/44475b6f-813a-4db0-bff0-cc3d7dd4eba1)

**All text/details displayed :**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8e338f63-7693-4dbd-a929-bfbd98f72053">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/a4b9e70d-03fe-4120-83a9-f8c048907125">


<img width="1728" alt="image" src="https://github.com/user-attachments/assets/fb1a2e5a-cb9a-4c53-af45-450d928f40a3">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/c9b1ce85-dbef-4c52-b50b-100e753dba2c">

**Comment by girishdigrajkar** [comment] 2024-10-09 09:42
This ticket could be closed as bullet point related issue is being tracked in  [FR: Text Formatting in [V2 Accordion] Block #858](https://github.com/hlxsites/vg-macktrucks-com/issues/858)

**Closed** 2024-10-10 06:59 UTC
Labels: Triage, Bugfix
