### ISSUE TITLE
Post go live- Major - Sub menu is not displayed for Technology >> Connected Business / Connected Driving

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#387] opened 2023-07-10 07:20 UTC
Steps:
1. Navigate to macktrucks.com
2. click on Technology
3. Click on Connected Business / Connected Driving
4. Validate the submenu

Expected result:
Submenu should be displayed 

Actual:
Submenu is not displayed

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/841cb046-e243-45df-9364-f4ff2b922ec2">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2594bc72-ba92-4684-a797-13d4d7af2fab">

**Comment by girishdigrajkar** [comment] 2023-07-10 08:41
2. Same issue for "Parts & service > Parts / Fleet"

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/a6f3adb3-3103-48c8-8ba9-b19443751d30">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/58d8d081-aff1-462a-a798-91b002802343">

**Comment by shirin27** [comment] 2023-07-24 11:39
@andreibalanescu can you re-check this? looks like the issue is still present.

**Comment by andreibalanescu** [comment] 2023-07-26 12:46
This is fixed now. @girishdigrajkar , can you please re-test? Thank you

**Comment by Andrei-Boiangiu** [comment] 2023-07-28 07:36
confirmed as fixed

**Closed by Andrei-Boiangiu** 2023-07-28 07:36 UTC
Labels: bug
